feat: add solution to problem [implement-omit-t-k]
BFEdev/BFE.dev-solutions pull request #22
Opened 2023-01-05 13:43 UTC by jiechen257

2023-01-07 11:17 UTC, BFEdev commented on typescript/implement-omit-t-k_en.md
> +  [P in keyof T as P extends K ? never : P]: T[P]
Thanks for contributing, could you add a bit more explanation on here ?
it's also worthy it to mention another approach `[P in Exclude<keyof T, K>]: T[P]`?

2023-01-07 11:18 UTC, BFEdev commented on typescript/implement-omit-t-k_en.md
> +Pay attention to `K extends keyof any`, K constraint is the key type of any Object
> `key type of any Object` 

Please make it clear here that it is `string | number | symbol`

2023-01-07 11:19 UTC, BFEdev requested changes
Thanks for contributing,

2023-01-08 04:52 UTC, jiechen257 commented
> Thanks for contributing,

Thank you for the suggestion. I have corrected and submitted it, please review again

2023-01-09 12:35 UTC, merged