Propose a solution to the "Remove Chars" problem
BFEdev/BFE.dev-solutions pull request #8
Opened 2022-11-06 04:02 UTC by AhmedIbrahim336

2022-11-07 23:35 UTC, BFEdev requested changes
Thanks for your contribution. Just one more step to get merged

2022-11-07 23:35 UTC, BFEdev commented on problem/remove-characters_en.md
> +  let stack: string[] = []
shall we use const?

2022-11-07 23:35 UTC, BFEdev commented on problem/remove-characters_en.md
> +    let char = input[i]
shall we use const?

2022-11-07 23:35 UTC, BFEdev commented on problem/remove-characters_en.md
> +8. Finaly, the last `a` in the input will be added to the stack. Stack will be `[c, a, a]` (**our output**)
it is a bit verbose here, shall we  align them  better? for example using a table

| char | stack | explanation|
|-----|-----|-----|
| c | [] | init|
| a | ['c'] | xxx
| b | ['c', 'a'] | xxx

2022-11-08 11:46 UTC, AhmedIbrahim336 commented on problem/remove-characters_en.md
> +  let stack: string[] = []
yup

2022-11-08 22:25 UTC, merged